### ISSUE TITLE
x86 seems to not be supported

### ISSUE THREAD

**Issue by NexInfinite** [AndranikSargsyan/pylsd-nova#1]
![image](https://user-images.githubusercontent.com/37962677/90315463-ad1db780-df13-11ea-8844-3880d5b6d3e4.png)
Why is `win32/x86/lsd.dll` not a thing, I think its why I am getting this import error `ImportError: Cannot load dynamic library. Did you compile LSD?`

**Comment by AndranikSargsyan** [comment]
The issue is solved in the new version (1.2.0). Closing the issue.
